### ISSUE TITLE
Dep example not showing viewlet? 

### ISSUE THREAD

**Issue by kevcunnane** [octref/explorer-api-example#1]
I'm using the latest Insiders build, and can see the Dep extension being loaded and the `vscode.workspace.registerTreeExplorerNodeProvider('depTree', new DepNodeProvider(rootPath));` line being executed. However the viewlet "Dependencies" is not showing up. Do you have any hints as to what I'm doing wrong? Do I need to run this against a VSCode build from source, or wait a few days for fixes in the insiders build?

**Comment by octref** [comment]
Try Command Palette -> Toggle Custom Viewlet.

Best,
Pine

**Comment by kevcunnane** [comment]
That worked - I now see the viewlet, but the provideRootNode() method is not being called. Any more ideas on what might be needed? 

![image](https://cloud.githubusercontent.com/assets/10819925/20202577/fdbac9ce-a774-11e6-9914-b7d4e01e67c9.png)

**Comment by octref** [comment]
Any error? Are you opening a workspace with node_modules?

**Comment by kevcunnane** [comment]
No visible errors. The workspace did have node_modules inside. The provideRootNode wasn't called so no chance to check for any modules in any case.

I will debug more tomorrow after updating insiders build, and see if I can find any uncaught error.

**Comment by octref** [comment]
I can repro it using latest Insider, but not with our master branch.
Let me ping you back when this is resolved.

**Comment by kevcunnane** [comment]
Great, with luck it will resolve itself with one of the next nightly builds. Thanks for the quick response!

**Comment by kevcunnane** [comment]
Updating to the latest Insiders build today, I see the API has changed from the workspace -> window  namespace. Unfortunately, I still see the same problem where the viewlet appears but no calls to get the root node are made. At this point I'll just wait to hear back from you when there's an Insiders build that supports this.

**Comment by octref** [comment]
~~Are you running the example in extension development mode? The API is still in preview and even in Insider we only enabled it for extension development mode.~~

NVM

**Comment by octref** [comment]
Fixed and will be available in the next Insider update.

**Comment by octref** [comment]
Don't know if we'll update Insider this afternoon. If you really want to play with it, try building from source -- it should only take a few minutes: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source
More doc will come next week.

**Comment by kevcunnane** [comment]
Thanks for the speedy turnaround!

**Comment by octref** [comment]
Today's insider build should be good.
- To run follower example you need to fill this line: https://github.com/octref/explorer-api-example/blob/master/follower/src/token.ts#L1
- To run redis example you need to have redis running. If not listening to the default port, change the `new IORedis()` in this file: https://github.com/octref/explorer-api-example/blob/master/redis/src/extension.ts to include the port like `new IORedis(4000)`.

More complete doc will come soon next week and published at VSCode website.

**Comment by kevcunnane** [comment]
Thanks - the Dependencies sample is working great now.
