### ISSUE TITLE
Question: Arbitrary UI inside of the sidebar viewlet

### ISSUE THREAD

**Issue by acromarco** [octref/explorer-api-example#2]
Hi @octref, 

Your work on https://github.com/Microsoft/vscode/pull/14048/files und especially the introduction of external viewlets seems like to lay the foundation for a more generic "extension defined viewlet" feature.

There is also https://github.com/Microsoft/vscode/issues/15217 which talks about "contributed viewlets", which seems to be related to the external viewlets that you have introduced.

Do you know more about this?

Are there any concrete plans if and when vscode will get this "contributed viewlets" extension ability? 
Will it be possible to add an arbitrary UI in this contributed viewlet, like for example an iframe that can communicate with the extension?

**Comment by octref** [comment]
> Are there any concrete plans if and when vscode will get this "contributed viewlets" extension ability?

We are exploring the best way to approach it. Not sure when.
The preview API is in Insider and doc will be published soon.

> Will it be possible to add an arbitrary UI in this contributed viewlet, like for example an iframe that can communicate with the extension?

No.
